apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-hazelcast
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-hazelcast"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.javaServer.hazelcast.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-hazelcast
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "devicehive.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end}}
      containers:
      - name: devicehive-hazelcast
        image: "{{ .Values.javaServer.repository }}/devicehive-hazelcast:{{ .Values.javaServer.tag }}"
        imagePullPolicy: {{ .Values.javaServer.PullPolicy }}
        env:
        - name: MIN_HEAP_SIZE
          value: {{ .Values.javaServer.hazelcast.minHeapSize | quote }}
        - name: MAX_HEAP_SIZE
          value: {{ .Values.javaServer.hazelcast.maxHeapSize | quote }}
        ports:
        - name: hazelcast
          containerPort: 5701
        resources:
{{ toYaml .Values.javaServer.hazelcast.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
