{{- if .Values.mqttBroker.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-mqtt-broker
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "mqtt-broker"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.mqttBroker.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-mqtt-broker
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "devicehive.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
      - name: mqtt-broker
        image: {{ .Values.mqttBroker.image | quote }}
        imagePullPolicy: {{ .Values.mqttBroker.PullPolicy }}
        env:
        - name: ENVSEPARATOR
          value: "_"
        - name: BROKER_ENABLE_PM
          value: "false"
        - name: BROKER_REDIS_SERVER_HOST
          value: "{{ .Release.Name }}-redis"
        - name: BROKER_REDIS_SERVER_PORT
          value: "6379"
        - name: BROKER_WS_SERVER_URL
          value: {{ .Values.mqttBroker.wsServerUrl | default "ws://localhost/api/websocket" | quote }}
        ports:
        - name: mqtt
          containerPort: 1883
        resources:
{{ toYaml .Values.mqttBroker.resources | indent 10 }}
{{- end }}
